apiVersion: v1
kind: Pod
metadata:
  name: fastapi-docker-e1
  namespace: default
  labels:
    app: fastapi-docker-e1
    version: v1
spec:
  containers:
    - name: fastapi-docker-e1
      image: 192.168.39.16:8082/docker/fastapi-docker-e1:0.0.2
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      lifecycle:
        preStop:
          exec:
            command: ["sleep", "30"]
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
  terminationGracePeriodSeconds: 30
        
